### PR TITLE
Update babel-brunch to fix JS compilation errors

### PR DESCRIPTION
**Pull request by danielkza**
With NPM 5.5.1 and NodeJS 8.9.3, attempting to compile the frontend JS
assets could fail with errors such as the ones below.

Update babel-brunch, and in turn the Babel presets, to fix it.

```
npm WARN deprecated coffee-script@1.10.0: CoffeeScript on NPM has moved
to "coffeescript" (no hyphen)
npm WARN deprecated babel-preset-es2016@6.24.1: 🙌  Thanks for using
Babel: we recommend using babel-preset-env now: please read
babeljs.io/env to update!
npm WARN deprecated babel-preset-es2015@6.24.1: 🙌  Thanks for using
Babel: we recommend using babel-preset-env now: please read
babeljs.io/env to update!
npm WARN bors_frontend No description
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.1.3
(node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for
fsevents@1.1.3: wanted {"os":"darwin","arch":"any"} (current:
{"os":"linux","arch":"x64"})

added 554 packages in 8.153s

> @ deploy /app/apps/bors_frontend
> brunch build --production

05 Jan 03:05:23 - error: Compiling of web/static/js/alert.js failed.
Couldn't find preset
"/app/apps/bors_frontend/node_modules/babel-preset-es2015" relative to
directory "web/static/js"
05 Jan 03:05:23 - error: Compiling of web/static/js/app.js failed.
Couldn't find preset
"/app/apps/bors_frontend/node_modules/babel-preset-es2015" relative to
directory "web/static/js"
05 Jan 03:05:23 - error: Compiling of web/static/js/drop-down-menu.js
failed. Couldn't find preset
"/app/apps/bors_frontend/node_modules/babel-preset-es2015" relative to
directory "web/static/js"
05 Jan 03:05:23 - error: Compiling of web/static/js/socket.js failed.
Couldn't find preset
"/app/apps/bors_frontend/node_modules/babel-preset-es2015" relative to
directory "web/static/js"
05 Jan 03:05:23 - error: Compiling of web/static/js/time-convert.js
failed. Couldn't find preset
"/app/apps/bors_frontend/node_modules/babel-preset-es2015" relative to
directory "web/static/js"
05 Jan 03:05:23 - info: compiled 2 files into app.css, copied 11 in
724ms
```

### CODE REVIEW

**Comment by danielkza** [comment]
It seems one build hung before starting and another failed to download something from hex.pm.

**Comment by notriddle** [comment]
Yeah.

bors r+

**Comment by notriddle** [comment]
Okay, I need to get off Travis and onto TC. Because this is ridiculous...

bors r+

**Comment by notriddle** [comment]
Seriously? Timed out while connecting to the database on *one* test?

bors r+

**Pull request merged**
