### PR TITLE
Add a UI for syncing reviewers and members

### LINKED ISSUE #409: Rely on Github permissions figure out read permissions for a repository
[Currently](407) making a user a "member" gives that user [limited](408) read-only access to the repository. Since Github actually comes with its own ACLs for Github reposes. Would it make sense to allow all users with read-access to a repo to also be able to see it in bors-ng (both dashboard and details as described in #408)?

### PR DESCRIPTION
**Pull request by notriddle**
Fixes #360
Fixes #409

### CODE REVIEW

**Comment by JensRantil** [comment]
👌 Unfortunately, I'm not too familiar with Elixir otherwise I would have reviewed this.

Also, you are a machine getting all these changes in quick! 💪  Thanks a lot! 💙

**Comment by JensRantil** [comment]
Just curious, does this PR also add automatic/periodic sync or does it still need a click in the repo settings to sync against Github?

**Comment by notriddle** [comment]
It doesn't add periodic sync.

**Comment by notriddle** [comment]
I added an issue to have it sync with the team / collaborators webhook.

**Pull request merged**
