### PR TITLE
Potential fix to check not being backlinked on some cases

### PR DESCRIPTION
**Pull request by umamaistempo**
Not tested. Marked as draft so I can get potential feedback; don't have access to the API, this is done solely based on it's docs

In theory it should handle the "check_run" events changing the batch status and adding the backlink. Best case scenario this solves issue #667; worst case scenario the batch is updated needlesly some times but ends with the expected final status just as it does right now.

### CODE REVIEW

**Comment by notriddle** [comment]
I have an instance of bors-ng that I run for testing this kind of stuff, running on Heroku. You could try running your fork on Heroku to see if it works.

**Comment by DilumAluthge** [comment]
Bump @notriddle @umamaistempo Any update on this?

**Comment by umamaistempo** [comment]
I did not do the test yet. Am considering doing a live stream for Elixir users between friday and saturday to showcase fixing the issues that I am assigned here on Bors. So, this is likely the fix but by the weekend I'll do a proper check (and then write tests and documentation).

If this is impacting your workflow considerably, I can take my time tomorrow to do it

**Comment by DilumAluthge** [comment]
Thanks for the update! This isn’t an urgent issue for me; I’m happy to wait until next weekend!

**Comment by umamaistempo** [comment]
Trying to set up a Bors instance on heroku to debug this

**Comment by DilumAluthge** [comment]
Bump. Any update on this?

**Comment by umamaistempo** [comment]
Great you asked, whatever excuses I have don't matter, but as a matter of fact, I was trying to complete my probational period without getting fired and seems to have succeded yay!

I am asking right now for my wife (as she is the one who is used to those ops things) to get the heroku up, will use this weekend (and the next few) to code open source, so, please, feel free to question/demand/??? if I don't get this updated by tomorrow. Now we're going to get back to the flow! :)

**Comment by notriddle** [comment]
Resolved by https://github.com/bors-ng/bors-ng/commit/2d3f13a6b47788a914297119e8f2a7acae485d33

For example, check out the links in https://github.com/bors-ng/bors-ng/pull/1002#issuecomment-673765958

**Pull request closed without merging**
