### PR TITLE
Add types to Database modules

### PR DESCRIPTION
**Pull request by umamaistempo**
- [x] Batch
- [x] Patch
- [x] Project
- [x] Attempt
- [x] AttemptStatus
- [x] Crash
- [ ] Installation
- [ ] LinkMemberProject
- [ ] LinkPatchBatch
- [ ] LinkUserProject
- [ ] Status
- [ ] User
- [ ] UserPatchDelegation

### CODE REVIEW

**Comment by notriddle** [comment]
Hey, @umamaistempo,

Is it okay if I merge this PR as it is? The modules where you've already added types seem pretty good, and I'd like to get these now in case someone else changes these files later and makes a merge conflict.

**Comment by umamaistempo** [comment]
Hey there @notriddle 

Sure, let me just commit the changes that I have on my local worktree on my home's personal computer :)

**Comment by umamaistempo** [comment]
@notriddle feel free to merge it

**Comment by notriddle** [comment]
Intermittent failure.

bors retry

**Pull request merged**
