### PR TITLE
implemented branch deleter

### PR DESCRIPTION
**Pull request by khodzha**

### CODE REVIEW

**Comment by khodzha** [comment]
not sure about tests ¯\_(ツ)_/¯

**Comment by notriddle** [comment]
I rebased it against master, fixed up the tests, and simplified a bit of stuff.

@khodzha would you like to look at what I did, see if everything makes sense?

**Comment by khodzha** [comment]
seems good to me

**Comment by notriddle** [comment]
bors r=notriddle,khodzha

**Comment by notriddle** [comment]
bors r=notriddle,khodzha

This has been a bunch of unrelated build flakiness. Sorry.

**Pull request merged**
