### PR TITLE
consistent batches order in batcher_test to avoid test flickering

### LINKED ISSUE #267: Flaking batcher tests
Seen on https://github.com/bors-ng/bors-ng/pull/256#issuecomment-322308353

### PR DESCRIPTION
**Pull request by khodzha**
Fixes #267

### CODE REVIEW

**Comment by notriddle** [comment]
You should probably change the PR description to "Fixes #267." That way, when your PR is merged, the issue will automatically be closed.

Also, I'm going to repeatedly retest this PR to see if I can trigger the test flickering.

bors try

**Comment by notriddle** [comment]
bors try

?

**Comment by notriddle** [comment]
Okay, apparently I'm not going to use bors try for awhile. GitHub is "[investigating reports of some undelivered webhooks](https://status.github.com/)."

**Comment by notriddle** [comment]
Cool, it got delivered.

bors try

**Comment by notriddle** [comment]
bors try

**Comment by notriddle** [comment]
bors try

**Comment by notriddle** [comment]
Looks solid to me.

Change your PR description so that it'll close the issue, then I'll r+ it.

**Comment by khodzha** [comment]
I performed 200 runs of test suite locally - no failed tests

**Comment by notriddle** [comment]
Cool, thanks.

bors r+

**Pull request merged**
