### PR TITLE
Get all statuses from the pagination

### LINKED ISSUE #1169: Follow pagination for statuses
The call to get the statuses for a commit should follow the pagination as in https://docs.github.com/en/rest/reference/repos#list-commit-statuses-for-a-reference 

Currently if a repository has too many statuses, bors ends up missing some and rejecting PRs for the `pr_status` rule.

### PR DESCRIPTION
**Pull request by dpp23**
Get all the pages from the status api both for statuses and checks.

An alternative approach will be to simply bump the page size to 100 which should be good enough for most projects. The current limit of 30 is however not enough.

Fixes #1169

### CODE REVIEW

**Comment by notriddle** [comment]
https://github.com/bors-ng/bors-ng/runs/1983668763

**Comment by dpp23** [comment]
> https://github.com/bors-ng/bors-ng/runs/1983668763

@notriddle sorry - wasn't aware of the formatter. Fixed now.

**Comment by notriddle** [comment]
No problem. I just switched CI provider, which left this a bit broken.

bors r+

**Pull request merged**
