### PR TITLE
Queue up attempts rather than running them all at once

### PR DESCRIPTION
**Pull request by notriddle**
https://forum.bors.tech/t/bors-try-doesnt-wait-untill-last-build-finishes/272

https://github.com/bors-ng/bors-ng/issues/434#issuecomment-434856549

### CODE REVIEW

**Comment by andschwa** [comment]
Thank you so much @notriddle!

(Also you asked on the forum why people might be using `bors try` instead of CI auto-building PRs. In my case, we have two reasons: (1) we don't want to auto-build PRs from just anyone, so `bors try` gives us a bit of an authentication layer, and (2) if we built every PR whenever they're opened/updated our CI would be so bogged down it would be useless.)

**Comment by notriddle** [comment]
(Please give your response on the forum, also, so that other people can see it.)

**Comment by notriddle** [comment]
No problem.

(I also copied your reply over to the forum, so that other participants would be able to see it.)

**Comment by andschwa** [comment]
Thank you! I don't have account there yet 😄

**Comment by andschwa** [comment]
login

new

🤷‍♂️

**Comment by notriddle** [comment]
Your adblocker has an outdated, or otherwise weird, filter policy.

**Comment by andschwa** [comment]
Ah, that is true! Good to know. Thanks again 😄

**Pull request merged**
