### PR TITLE
Link to a project's build history in the commit status

### PR DESCRIPTION
**Pull request by grahamc**
When creating a status report, place a link to the project's historic logs to show some context for the batch.

Demonstrated working here: https://github.com/tweag/bors-test/pull/13#event-1485632507

### CODE REVIEW

**Comment by grahamc** [comment]
The line length issues are going to be trivial to fix, but I'd appreciate some guidance on:

```
== apps/bors_github/lib/github.ex ==
133: FunctionArity: Arity of `post_commit_status!` should be less than 4 (was 5).
```

**Comment by notriddle** [comment]
The style checker is mad at you, but otherwise :+1:

```
147 files, 4 errors!
== apps/bors_github/lib/github.ex ==
133: FunctionArity: Arity of `post_commit_status!` should be less than 4 (was 5).
== apps/bors_github/lib/github/server_mock.ex ==
294: LineLength: Line length should not exceed 80 chars (was 83).
== apps/bors_worker/lib/batcher.ex ==
545: LineLength: Line length should not exceed 80 chars (was 97).
553: LineLength: Line length should not exceed 80 chars (was 97).
```

**Comment by notriddle** [comment]
Probably change it to accept a map instead of just having the arguments be individually given.

**Comment by grahamc** [comment]
I'd like the opportunity to squash these prior to it merging. Also, I'm about to test it in a production environment now.

**Comment by grahamc** [comment]
Great, tests pass! How does this look now?

FWIW I'm looking at a couple additional features:

1. somehow highlighting the batch when viewing the log page
2. sending a commit status for Try calls

**Comment by grahamc** [comment]
:( I don't know how to fix this:

```
Compiling 23 files (.ex)
warning: function BorsNG.Endpoint.broadcast!/3 is undefined (module BorsNG.Endpoint is not available)
  lib/project.ex:20
```

**Comment by notriddle** [comment]
The warning isn't the problem. The problem is some distance below, where it says `** (CompileError) lib/batcher.ex:34: module BorsNG.Router.Helpers is not loaded and could not be found`

We should probably abandon the "umbrella app" setup. It's not really buying us anything, and it gets mad about "circular dependencies" like th worker -> frontend -> worker dependency that's been created here.

**Comment by grahamc** [comment]
Ok, that is almost definitely something I'm not qualified to do. Is my best bet for now to let this PR sit until that happens?

**Comment by notriddle** [comment]
Yeah, I'm working on it right now...

**Comment by grahamc** [comment]
Oh! Jeeze, amazing, I need to get a gig like yours :grin:

**Comment by notriddle** [comment]
Yeah, once the other guy arrives I'll probably have to drop this and do actual work. So it probably won't be ready today.

**Comment by grahamc** [comment]
OK I've rebased this on to #356 and it continues to work properly.

**Comment by grahamc** [comment]
:tada: thank you for helping me through my first PR!

**Comment by notriddle** [comment]
No problem. Thank you for putting so much work into this thing! :+1:

**Pull request merged**
