### PR TITLE
Allow public repos to have public queues

### LINKED ISSUE #202: There is no good reason for the public instance to not show the queue to anyone who wants to see it
Of course, random passers-by shouldn't be able to trigger a Synchronize or Cancel All or change around branches.

### PR DESCRIPTION
**Pull request by notriddle**
Fixes #202

### CODE REVIEW

**Comment by Macarse** [comment]
LGTM 👍

**Comment by notriddle** [comment]
Doesn't look good to dialyzer, though. 😞

**Comment by notriddle** [comment]
This should fix it, though.

bors r+

**Comment by notriddle** [comment]
bors r=Macarse,jniles

**Pull request merged**
