### PR TITLE
checks for toml file in .github

### PR DESCRIPTION
**Pull request by veverkap**
Fixes https://github.com/bors-ng/bors-ng/issues/212

### CODE REVIEW

**Comment by veverkap** [comment]
Redoing #221

**Comment by notriddle** [comment]
Okay, that should be the last fix.

bors r+

**Comment by notriddle** [comment]
Thanks for contributing, @veverkap! Are you using bors-ng internally somewhere? I notice you don't have any repos in the public instance.

(Sorry this was such a bumpy ride; totally my fault about pushing to the branch incorrectly...)

**Comment by veverkap** [comment]
No worries at all. I've been following the project for a while and we will
probably use it internally.

**Pull request merged**
