### PR TITLE
Add `npm install` to the setup script

### PR DESCRIPTION
**Pull request by notriddle**
I forgot that step.

### CODE REVIEW

**Comment by Macarse** [comment]
:+1:

**Comment by Macarse** [comment]
@notriddle I still don't see the image :(

> web_1       | [info] GET /images/a.svg
> web_1       | [info] GET /css/app.css
> web_1       | [debug] ** (Phoenix.Router.NoRouteError) no route found for GET /images/a.svg (BorsNG.Router)
> web_1       |     (bors_frontend) web/router.ex:1: BorsNG.Router.match_route/4
> web_1       |     (bors_frontend) web/router.ex:1: BorsNG.Router.do_call/2
> web_1       |     (bors_frontend) lib/bors_ng/endpoint.ex:1: BorsNG.Endpoint.phoenix_pipeline/1
> web_1       |     (bors_frontend) lib/plug/debugger.ex:123: BorsNG.Endpoint."call (overridable 3)"/2
> web_1       |     (bors_frontend) lib/bors_ng/endpoint.ex:1: BorsNG.Endpoint.call/2
> web_1       |     (plug) lib/plug/adapters/cowboy/handler.ex:15: Plug.Adapters.Cowboy.Handler.upgrade/4
> web_1       |     (cowboy) /Users/csessa/Documents/bors-ng/deps/cowboy/src/cowboy_protocol.erl:442: :cowboy_protocol.execute/4
> web_1       | 
> web_1       | [debug] ** (Phoenix.Router.NoRouteError) no route found for GET /css/app.css (BorsNG.Router)
> web_1       |     (bors_frontend) web/router.ex:1: BorsNG.Router.match_route/4
> web_1       |     (bors_frontend) web/router.ex:1: BorsNG.Router.do_call/2
> web_1       |     (bors_frontend) lib/bors_ng/endpoint.ex:1: BorsNG.Endpoint.phoenix_pipeline/1
> web_1       |     (bors_frontend) lib/plug/debugger.ex:123: BorsNG.Endpoint."call (overridable 3)"/2
> web_1       |     (bors_frontend) lib/bors_ng/endpoint.ex:1: BorsNG.Endpoint.call/2
> web_1       |     (plug) lib/plug/adapters/cowboy/handler.ex:15: Plug.Adapters.Cowboy.Handler.upgrade/4
> web_1       |     (cowboy) /Users/csessa/Documents/bors-ng/deps/cowboy/src/cowboy_protocol.erl:442: :cowboy_protocol.execute/4
> web_1       | 
> web_1       | [info] GET /js/app.js
> web_1       | [debug] ** (Phoenix.Router.NoRouteError) no route found for GET /js/app.js (BorsNG.Router)
> web_1       |     (bors_frontend) web/router.ex:1: BorsNG.Router.match_route/4
> web_1       |     (bors_frontend) web/router.ex:1: BorsNG.Router.do_call/2
> web_1       |     (bors_frontend) lib/bors_ng/endpoint.ex:1: BorsNG.Endpoint.phoenix_pipeline/1
> web_1       |     (bors_frontend) lib/plug/debugger.ex:123: BorsNG.Endpoint."call (overridable 3)"/2
> web_1       |     (bors_frontend) lib/bors_ng/endpoint.ex:1: BorsNG.Endpoint.call/2
> web_1       |     (plug) lib/plug/adapters/cowboy/handler.ex:15: Plug.Adapters.Cowboy.Handler.upgrade/4
> web_1       |     (cowboy) /Users/csessa/Documents/bors-ng/deps/cowboy/src/cowboy_protocol.erl:442: :cowboy_protocol.execute/4

**Comment by notriddle** [comment]
You'll need to run setup again if you haven't run it since upgrading, since setup is what gets modified.

**Comment by Macarse** [comment]
yep, I did that. I run setup first.

**Comment by Macarse** [comment]
@notriddle it's fixed now... sorry :(

**Pull request merged**
