### PR TITLE
Gracefully handle when a push to `into_branch` results in a non-fast-forward error

### PR DESCRIPTION
**Pull request by noizwaves**
This PR introduces a fix for the issue reported in https://github.com/bors-ng/bors-ng/issues/856.

## Scenario
The `into_branch` changes, either from a manually merged PR or directly pushed to while a Bors batch is running.

## Previously
Bors would attempt to push to the `into_branch`, receive an error from the GitHub API, and then crash:

```
{{:badmatch,
  {:error, :push, 422,
   "{\"message\":\"Update is not a fast forward\",\"documentation_url\":\"https://developer.github.com/v3/git/refs/#update-a-reference\"}"}},
 [
   {BorsNG.Worker.Batcher, :complete_batch, 3,
    [file: 'lib/worker/batcher.ex', line: 518]},
   {BorsNG.Worker.Batcher, :maybe_complete_batch, 1,
    [file: 'lib/worker/batcher.ex', line: 499]},
   {BorsNG.Worker.Batcher, :handle_cast, 2,
    [file: 'lib/worker/batcher.ex', line: 84]},
   {:gen_server, :try_dispatch, 4,
    [file: 'gen_server.erl', line: 637]},
   {:gen_server, :handle_msg, 6,
    [file: 'gen_server.erl', line: 711]},
   {:proc_lib, :init_p_do_apply, 3,
    [file: 'proc_lib.erl', line: 249]}
 ]}
```

## New Behavior
The code checks to see if the push failed due to a non-fast-forward update error, and then retries the batch again (without a bisect). This seems safe and efficient to do, as the batch has already built successfully at this point.

These pictures demonstrate the new behavior. In this scenario, PR 107 and 108 were enqueued into bors and when the batch started to run, a third PR was directly merged:

Screenshot showing the history that experienced an update to into_branch

The comment history for an affected PR in the batch

<Picture of comment history on PR>

## The changes
Some of the code changes were a result of changing the signature of `Batcher.complete_batch/3` to return new state. This was required to model the fact a Batch could take a new path and change to `:error` after being `:ok`.

The meaningful changes happen in `Batcher.complete_batch/3` where we match on the `push_success = false` case.

The behavior of `ServerMock` was also enhanced to exhibit specific kinds of failures for the `:push` message.

### CODE REVIEW

**Comment by notriddle** [comment]
Fix the dialyzer errors, then I'll merge it.

https://community-tc.services.mozilla.com/tasks/Kf3HsFtLTcGYIWRUMcAimw/runs/0/logs/https%3A%2F%2Fcommunity-tc.services.mozilla.com%2Fapi%2Fqueue%2Fv1%2Ftask%2FKf3HsFtLTcGYIWRUMcAimw%2Fruns%2F0%2Fartifacts%2Fpublic%2Flogs%2Flive.log

**Comment by noizwaves** [comment]
@notriddle Thanks for the feedback! I've fixed the dialyzer errors. The fix doesn't look great, but I'm unsure how to make it look cleaner.

**Comment by noizwaves** [comment]
@notriddle hey, just wanted to bump this PR to see if it could be merged now. Thanks in advance!

**Comment by notriddle** [comment]
Sure, let's merge this.

**Pull request merged**
