### PR TITLE
Add custom commit titles

### LINKED ISSUE #637: Functionality to customise commit titles/bodies
Hi, thanks for the wonderful bot!

[I noticed on the bors-ng forum](https://forum.bors.tech/t/how-to-change-the-commit-message-format/307) that this functionality isn't done yet but there was no opposition to the idea. I had a look around the code and found where the commit messages from [bors are being templated](https://github.com/bors-ng/bors-ng/blob/239932148799c77313d092433ef7ff1c01bc82f0/lib/worker/batcher/message.ex#L88-L111). 

I was feeling something like the branch name (a la GitHub) or even the PR title might be useful things to allow, e.g. `Merge pull request #123 from justanotherdot/topic/use_bors` or `Merge #123: Start using bors` respectively. Obviously there's a number of attributes that could be used and providing a simple way to customise it would be handy, but possibly complex depending on the approach. Would love to know your thoughts on the matter.

### PR DESCRIPTION
**Pull request by korthout**
This PR adds the ability to customise commit titles using a new
config property: `commit_title`.

To maintain backwards compatibility, the commit_title defaults to
`Merge ${PR_REFS}`. The hardcoded token `${PR_REFS}` is replaced with
the available patchlinks' xrefs.

The commit_title can be configured in the Bors Toml.

closes #637

### CODE REVIEW

**Comment by korthout** [comment]
Hi there, Bors team! I've been using your tool for some time now, and I really like it. 

I thought it would be a good addition to allow customising commit titles, as discussed in #637. It would make me and my team happy if we could have such an ability. I've taken the liberty to just implement it in a way that I saw fit, since there was no further design discussion in the issue. But please let me know if I can change anything to better fit your coding style. For example, I've chosen a new configuration property name (`commit_title`), and a hardcoded token (`${PR_REFS}`) which I just chose, but should probably be discussed before anything.

Please let me know what you think. 

PS: This is my first Elixer PR, please be gentle 🙂

**Comment by notriddle** [comment]
This doesn't look bad, but since it's adding a new configuration option, it should probably be presented to the RFC peanut gallery. Could you open an RFC on https://forum.bors.tech/c/development/draft-rfcs/11 ?

**Comment by korthout** [comment]
Hi @notriddle. I've opened one here: https://forum.bors.tech/t/rfc-add-support-for-custom-commit-titles/516. Please have a look

**Review by notriddle — APPROVED** [review]
bors r+

**Comment by korthout** [comment]
@notriddle I see you merged this, but not all of the requested changes from the RFC were represented in this PR. Let me know if you need me to help out.

**Comment by notriddle** [comment]
I merged it anyway because it wasn't making any progress and it wasn't worth it to me to keep delaying on those feedback items. If it becomes a problem, we can always add a "custom titles v2", and keep the old one around as a compatibility hack.

If there's anything in here that you think needs fixed, you can open another PR to try to fix them, but I'm pretty sure this version will satisfy your needs and a lot of other peoples'.

**Pull request merged**
