### PR TITLE
Batch per code owner

### PR DESCRIPTION
**Pull request by gmendonca**
Working to try to fix the issues presented on: https://github.com/bors-ng/bors-ng/issues/754

I was thinking to avoid batching together patches with different code owners. Not sure if it's the best approach, so feedbacks are welcome here.

### CODE REVIEW

**Comment by notriddle** [comment]
You know what?

How often do you expect two patches to have the same code owner? If the answer is "not very often", maybe we should just disable batching in the presence of a `CODEOWNERS` file? It would be a lot simpler.

**Comment by gmendonca** [comment]
In my situation, sometimes we are trying to merge 10-12 PRs with different code owners and they all are cascading failing because of 422 errors.

What I normally do in this scenario is: I manually separate PRs with the same `CODEOWNERS` with the same priority using `bors r+ p=`. However this is a very dull and manual process.

**Comment by notriddle** [comment]
That's not really my question.

My question is: since we're already separating them by priority, and by branch name, by mergeability, and now separating them by code owner. With all these different things forcing separate batches, are we still going to perform enough batching to make it worthwhile having it at all? I'm wondering if it would make any difference if we just disabled batching entirely instead of trying to be smart about it.

**Comment by gmendonca** [comment]
Yeah, you got a really good point. 

Normally I would expect, in the `CODEOWNERS` situation, to have `* @my_org/team_name` in which most of the files would fall into, and some more restrictives rules after it. I would expect to have more PRs being batched together that falls into the general rule, and few more restrictives ones not being batched together.

But again, you got a really good point. Since `bors` is done to be generic, in a sense, if someone is using `CODEOWNERS` in a different way, it would potentially lead to not batching PRs at all.

**Comment by notriddle** [comment]
> Normally I would expect, in the CODEOWNERS situation, to have * @my_org/team_name in which most of the files would fall into, and some more restrictives rules after it.

If that's what you're doing, then *awesome*, my concerns have been answered 🎉 . We can continue this PR with confidence that it will actually be useful to someone.

**Comment by gmendonca** [comment]
Closing as the solutions is to only rely on bors to validate if there's a code owner approval or not. Letting both Github and bors with this enable lead to problems described here: https://github.com/bors-ng/bors-ng/issues/754

**Pull request closed without merging**
