### PR TITLE
accept bors commands with a colon

### LINKED ISSUE #219: Accept bors commands with a colon
https://github.com/georust/rust-geo/pull/120

### PR DESCRIPTION
**Pull request by khodzha**
pr for issue #219
not sure if _parse is appropriate name for a function tho :thinking: 

*Edit by @notriddle: fixes #219*

### CODE REVIEW

**Comment by Macarse** [comment]
We are already reporting back when the command was nor parsed correctly. I think this should be the same. Instead of accepting `bors: +r` bors should post saying: "Did you mean ..."

see https://github.com/bors-ng/bors-ng/pull/214

**Comment by notriddle** [comment]
If you want suggestions, you could name the new function `parse_cmd` and rename the current function with that name to `parse_trimmed_cmd`.

**Comment by notriddle** [comment]
@Macarse

Unlike the case of actual misspelled commands, I'm not sure what the advantage of rejecting `bors: r+` is. It's obvious what the user means when they type that.

This PR only adds the `:` as a permitted delimiter between "bors" and the command. It doesn't make it accept `+r` as the review command.

**Comment by Macarse** [comment]
@notriddle because you are extending the API. If `bors: r+` is accepted, I also want `bors; r+`.

Why do we want to add this? To make sure developers do not waste time waiting for a build that never started?
Considering this a misspelled command would notify the developer immediately.

**Comment by khodzha** [comment]
im not actually a bors-ng user, yet `bors: r+` seems meaningful, `bors; r+` does not
but i agree that bloating allowed separators can be a problem

**Comment by notriddle** [comment]
> Why do we want to add this? To make sure developers do not waste time waiting for a build that never started?

Mostly because it's a common thing I see homu users doing. I've already had to teach people who're migrating not to start the bot's name with an `@` sign and that the command has to go on its own line. The "own line" thing is a restriction that I'm still not sure if I'm comfortable with, but at least there I can name an actual tradeoff in its favor (it reduces false positives like when people talk *about* bors's commands).

Carrying the colon thing into perpetuity seems like such a tiny burden compared to all the other compatibility stuff that bors-ng does.

**Comment by notriddle** [comment]
@khodzha And thanks for putting up with our last-minute bickering. Honestly, it's kind of embarrassing that we haven't already resolved this 😞

**Comment by notriddle** [comment]
To summarize: I filed issue #219 because it seemed like a good idea to make bors-ng's syntax more like homu's. To reduce friction for people migrating to it.

**Comment by notriddle** [comment]
@khodzha ... And thank you for putting up with the 80char line limit. 😁

**Comment by Macarse** [comment]
> because it seemed like a good idea to make bors-ng's syntax more like homu's. To reduce friction for people migrating to it.

Posting a msg in the PR with the "Did you mean bors r+" also reduces the friction and teaches the user the correct way and unique way of executing actions.

@notriddle As mentioned in the previous PR, this is your call. You should be the one making the final decision on the API we support.

**Comment by notriddle** [comment]
Sure, okay.

bors r+

Next time, though, I'm opening a B-RFC issue before putting API-affecting changes on E-easy. Dropping an API design discussion on a first-time contributor is not the kind of environment that I think anyone wants to create for first-timers.

**Comment by notriddle** [comment]
And thanks for showing up and (essentially) beta-testing the decision-making process, @khodzha.

**Comment by khodzha** [comment]
you are welcome! :smiley:

**Comment by notriddle** [comment]
Welp, that's done. It should be getting deployed to the test instance in a few minutes, and then it'll be ready for everyone to use.

**Comment by notriddle** [comment]
[And... there it goes!](https://github.com/notriddle/test_repo/pull/100)

**Comment by Macarse** [comment]
@notriddle 100% agree.
@khodzha sorry for the discussion in your first PR! Second will go faster for sure 👍

**Comment by khodzha** [comment]
no need for excuses, it was important thing to clear up

**Pull request merged**
