### PR TITLE
empty? helper functions for #22 and #23

### PR DESCRIPTION
**Pull request by abeltensor**
Added two helpers to the page_view.ex and project_view.ex views and then implemented these functions to solve issues #22 and #23.

Please check my code, was unable to rebuild the full project on my localhost the 2nd time
(should work fine though).

### CODE REVIEW

**Comment by notriddle** [comment]
I'm sorry to inform you that [your code is not valid](https://travis-ci.org/bors-ng/bors-ng/jobs/282833235). Your template tries to call `is_empty?`, but you actually named the function `empty?`.

**Comment by notriddle** [comment]
I'm not sure if you realized this, but these two function definitions are equivalent:

```elixir
# Both of these are valid Elixir

# Notice how the single-line version has no `end` keyword, but does have a comma (`,`) and a colon (`:`)
fn empty?(list) when is_list(list), do: false

# Notice how the multi-line version has no comma (`,`) or colon (`:`), but does have an `end` keyword
fn empty?(list) when is_list(list) do
  false
end
```

You wrote something like this, which is not valid.

```elixir
# This is not valid Elixir. The single-line version has no `end` keyword.
fn empty?(list) when is_list(list) do false end
```

https://hexdocs.pm/elixir/1.5/syntax-reference.html is really useful for this stuff.

**Comment by abeltensor** [comment]
Whitespace should be completely gone now.

**Comment by abeltensor** [comment]
Looks like the travis ci build is finally going to work.  

Problem with whitespace came from using the github editor.  I figured such a small change would be more easily implemented this way (I stand corrected).  

Problem with function name was simply my own negligence.  

Hopefully everything else works out as intended; this is technically my first collaboration so I hope you will forgive the hiccups.

**Comment by notriddle** [comment]
No problem, it's not like your actually hurting anything, 🤷‍

Besides, the whole point of having Easy Issues lying around is so that people can learn how to perform all the ceremony without simultaneously having to diagnose complicate component interaction puzzles. 😖

So, mission accomplished.

bors r+

**Comment by abeltensor** [comment]
Thank you.  Yes it is a learning experience.  At least I know I should probably just push everything from emacs next time instead of using the github editor haha.

**Comment by notriddle** [comment]
By the way, about:

> Please check my code, was unable to rebuild the full project on my localhost the 2nd time (should work fine though).

What kind of problem was preventing you from building it locally? Was it just the same errors that Travis gave, or were you AFK, or something else?

**Comment by abeltensor** [comment]
so i am building on windows, the error I got had to do with one of the private functions in the router not being able to find a user.  

When I built it last night, there were not problems like that; I try rebuilding it again and see if there is a problem.  Its very likely that I just didn't install all of the node dependencies properly.

**Pull request merged**
